### ISSUE TITLE
Sanity functions with closures might result in unexpected behaviour

### ISSUE THREAD

**Issue by vkarak** [eth-cscs/reframe#627]
Here is an example:

```python
import reframe as rfm
import reframe.utility.sanity as sn


@rfm.simple_test
class SSHLoginEnvCheck(rfm.RunOnlyRegressionTest):
    def __init__(self):
        super().__init__()
        self.descr = ('Check if a set of environment variables is '
                      'defined when accessing remotely over SSH')
        self.valid_systems = ['daint:login', 'dom:login']
        self.valid_prog_environs = ['PrgEnv-cray']
        reference = {
            'CRAY_CPU_TARGET': 'haswell',
            'CRAYPE_NETWORK_TARGET': 'aries',
            'MODULEPATH': r'[\S+]',
            'MODULESHOME': r'/opt/cray/pe/modules/[\d+\.+]',
            'PE_PRODUCT_LIST': 'CRAYPE_HASWELL:CRAY_RCA:CRAY_ALPS:DVS:'
                               'CRAY_XPMEM:CRAY_DMAPP:CRAY_PMI:CRAY_UGNI:'
                               'CRAY_UDREG:CRAY_LIBSCI:CRAYPE:CRAY:'
                               'PERFTOOLS:CRAYPAT',
            'SCRATCH': r'/scratch/[\S+]',
            'XDG_RUNTIME_DIR': r'/run/user/[\d+]'
        }
        self.executable = 'ssh'
        echo_args = ' '.join('%s=$%s' % (i, i)  for i in reference.keys())
        self.executable_opts = [self.current_system.name,
                                'echo', "'%s'" % echo_args]
        self.sanity_patterns = sn.all(
            sn.map(lambda x: sn.assert_found(x, self.stdout), ['CRAY_CPU_TARGET=haswell']))
        self.maintainers = ['RS', 'LM']
        self.tags = {'maintenance'}
```

This produces the following error:

```
FAILURE INFO for SSHLoginEnvCheck
  * System partition: dom:login
  * Environment: PrgEnv-cray
  * Stage directory: /users/karakasv/Devel/reframe/stage/dom/login/PrgEnv-cray/SSHLoginEnvCheck
  * Job type: local (id=3983)
  * Maintainers: ['RS', 'LM']
  * Failing phase: sanity
  * Reason: unexpected error: 'NoneType' object has no attribute 'stdout'
Traceback (most recent call last):
  File "/users/karakasv/Devel/reframe/reframe/frontend/executors/__init__.py", line 58, in _safe_call
    return fn(*args, **kwargs)
  File "/users/karakasv/Devel/reframe/reframe/core/pipeline.py", line 1060, in sanity
    self.check_sanity()
  File "/users/karakasv/Devel/reframe/reframe/core/pipeline.py", line 1078, in check_sanity
    success = evaluate(self.sanity_patterns)
  File "/users/karakasv/Devel/reframe/reframe/core/deferrable.py", line 344, in evaluate
    return expr.evaluate()
  File "/users/karakasv/Devel/reframe/reframe/core/deferrable.py", line 52, in evaluate
    ret = self._fn(*fn_args, **fn_kwargs)
  File "/users/karakasv/Devel/reframe/reframe/utility/sanity.py", line 117, in all
    return builtins.all(iterable)
  File "/users/karakasv/Devel/reframe/reframe/core/deferrable.py", line 63, in __bool__
    return builtins.bool(self.evaluate())
  File "/users/karakasv/Devel/reframe/reframe/core/deferrable.py", line 45, in evaluate
    arg.evaluate() if isinstance(arg, type(self)) else arg)
  File "/users/karakasv/Devel/reframe/reframe/core/deferrable.py", line 52, in evaluate
    ret = self._fn(*fn_args, **fn_kwargs)
  File "/users/karakasv/Devel/reframe/reframe/core/pipeline.py", line 689, in stdout
    return self._job.stdout
AttributeError: 'NoneType' object has no attribute 'stdout'
```

The problem is that we deep copy the regression test object before running it for each programming environment and system partition, but the function closures are not deep copied. As a result, `self` in the above example refers to the original object, thus leading to this error.

This bug is another limitation of the deep copying of regression tests described in #55.

**Workaround**: Avoid sanity function with mutable closures. The above example could be rewritten as follows:

```python
    def __init__(self):
        ...
        self.sanity_patterns = sn.all(
            sn.map(self.assert_envvar, ['CRAY_CPU_TARGET=haswell']))

    def assert_envvar(self, v):
        return sn.assert_found(v, self.stdout)
```

**Comment by vkarak** [comment]
As discussed in #55, we are not going to eliminate deep copying of the test instances, so I am marking this issue as "wontfix." We should instead at a note in the documentation.
